[tool.kedro]
package_name = "kedro_dynamic_pipeline_hook_example"
project_name = "kedro-dynamic-pipeline-hook-example"
kedro_init_version = "0.18.12"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/kedro_dynamic_pipeline_hook_example -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
